#!/usr/bin/env bash

# Download the latest release from GitHub
wget $(curl -s https://api.github.com/repos/noisetorch/Noisetorch/releases/latest | grep "browser_download_url.*.tgz\"" | cut -d : -f 2,3 | tr -d \")

# Extract the archive to your local profile directory
tar -C $HOME -h -xzf NoiseTorch_*.tgz

# Remove the archive
rm -f NoiseTorch_*.tgz

# Refresh icon cache
gtk-update-icon-cache

# Give NoiseTorch its required permissions
sudo setcap 'CAP_SYS_RESOURCE=+ep' ~/.local/bin/noisetorch

# Make sure that is in your PATH
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# Create autostart directory, if not already present
mkdir -p ~/.config/autostart

# Add to autostart at login
echo "[Desktop Entry]
Type=Application
Name=Enable NoiseTorch
Comment=Enables NoiseTorch Virtual Microphone 
Exec=noisetorch -i
StartupNotify=false
Terminal=false" >> ~/.config/autostart/noisetorch.desktop

# Remove script after completion
rm -- "$0"
